### ISSUE TITLE
NoSuchMethodError when trying to generate a Client from a GraphQL config

### ISSUE THREAD

**Issue by zetcco** [ballerina-platform/graphql-tools#218]
**Description:**
Tried to follow the [Client generation from GraphQL Config](https://ballerina.io/learn/graphql-tool/#generate-a-client-from-a-graphql-config) and resulted in a `NoSuchMethodError`.
Same thing was done with the version `2201.6.0` and it worked without any errors.

```
[2023-09-01 16:18:08,275] SEVERE {b7a.log.crash} - 'void org.yaml.snakeyaml.constructor.Constructor.<init>(java.lang.Class)'
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.constructor.Constructor.<init>(java.lang.Class)'
        at io.ballerina.graphql.cmd.Utils.getProcessedConstructor(Utils.java:68)
        at io.ballerina.graphql.cmd.GraphqlCmd.readConfig(GraphqlCmd.java:251)
        at io.ballerina.graphql.cmd.GraphqlCmd.generateClient(GraphqlCmd.java:206)
        at io.ballerina.graphql.cmd.GraphqlCmd.executeOperation(GraphqlCmd.java:188)
        at io.ballerina.graphql.cmd.GraphqlCmd.execute(GraphqlCmd.java:134)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:56)
```

**Affected Product Version:**
Ballerina 2201.7.2 (Swan Lake Update 7)
Language specification 2023R1
Update Tool 1.3.15

**OS, DB, other environment details and versions:**    
Windows 11 - 22H2

**Steps to reproduce:**
Follow these steps on the doc: https://ballerina.io/learn/graphql-tool/#generate-a-client-from-a-graphql-config

**Comment by DimuthuMadushan** [comment]
This occurs in `2201.8.0` as well.
```shell
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-09-06 12:52:13,066] SEVERE {b7a.log.crash} - JSONObject["data"] not found. 
org.json.JSONException: JSONObject["data"] not found.
        at org.json.JSONObject.get(JSONObject.java:570)
        at io.ballerina.graphql.generator.client.Introspector.getIntrospectionResult(Introspector.java:74)
        at io.ballerina.graphql.cmd.Utils.getGraphQLSchemaDocument(Utils.java:99)
        at io.ballerina.graphql.cmd.Utils.validateGraphqlProject(Utils.java:190)
        at io.ballerina.graphql.cmd.GraphqlCmd.generateClient(GraphqlCmd.java:279)
        at io.ballerina.graphql.cmd.GraphqlCmd.executeOperation(GraphqlCmd.java:255)
        at io.ballerina.graphql.cmd.GraphqlCmd.execute(GraphqlCmd.java:164)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```
